variables:
  NAMESPACE: platform

stages:
  - build

build:
  stage: build
  image: registry.trendyol.com/platform/base/image/docker:19.03.9-dind
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - make docker-build docker-push IMG="registry.trendyol.com/platform/base/apps/ratelimit-operator:0.0.1" 


