# permissions for end users to view globalratelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalratelimit-viewer-role
rules:
- apiGroups:
  - trendyol.com
  resources:
  - globalratelimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trendyol.com
  resources:
  - globalratelimits/status
  verbs:
  - get
