# permissions for end users to edit localratelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localratelimit-editor-role
rules:
- apiGroups:
  - trendyol.com
  resources:
  - localratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trendyol.com
  resources:
  - localratelimits/status
  verbs:
  - get
