
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - trendyol.com
  resources:
  - globalratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trendyol.com
  resources:
  - globalratelimits/finalizers
  verbs:
  - update
- apiGroups:
  - trendyol.com
  resources:
  - globalratelimits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - trendyol.com
  resources:
  - localratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trendyol.com
  resources:
  - localratelimits/finalizers
  verbs:
  - update
- apiGroups:
  - trendyol.com
  resources:
  - localratelimits/status
  verbs:
  - get
  - patch
  - update
