apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ratelimit-operator-leader-election-role
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ratelimit-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: ratelimit-operator
  namespace: platform
