## Append samples you want in your CSV to this file as resources ##
resources:
- trendyol.com_v1beta1_localratelimit.yaml
- trendyol.com_v1beta1_globalratelimit.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
